### ISSUE TITLE
cl_interface should add source command to /etc/network/interface

### ISSUE THREAD

**Issue by trapier** [CumulusNetworks/cumulus-linux-ansible-modules#22]
# Issue
`cl_interface` module does not add a `source` line to `/etc/network/interfaces` for the location of the ansible-generated interface config files.

# Versions
* ansible 1.8.4
* cumulus-linux-ansible-modules db00cc0b8ea4684f8bc4a2b5502012897985de2e
* Cumulus Linux 2.5.1

# Steps to Reproduce
1. Tell `cl_interface` to configure an interface.

    Playbook:

        ---
        # file: test.yml
        - hosts: sw1
          sudo: yes
          tasks:
          - name: configure swp1
            cl_interface: name=swp1 ipv4="10.1.1.1/32"

    Run:

        $ ansible-playbook test.yml

        PLAY [sw1] ********************************************************************

        GATHERING FACTS ***************************************************************
        ok: [sw1]

        TASK: [configure swp1] ********************************************************
        changed: [sw1]

        PLAY RECAP ********************************************************************
        sw1                        : ok=2    changed=1    unreachable=0    failed=0

# Observed Behavior
`/etc/network/interfaces.d/*` is populated correctly:

    root@sw1:~# cat /etc/network/interfaces.d/swp1
    auto swp1                                     
    iface swp1                                    
            address 10.1.1.1/32                   

But there is no link created from `/etc/network/interfaces` to `/etc/network/interfaces.d/*`.

    root@sw1:~# ifquery swp1           
    error: cannot find interfaces: swp1

# Expected Behavior
The reference  `source {{cl_interface.location}}` is present in `/etc/network/interfaces`.

**Comment by trapier** [comment]
Or: docs need updating to state that the source line needs to be added by an independent task.

**Comment by skamithi** [comment]
doc will be updated in cl_interface, cl_bond and cl_bridge to say that source line must be /etc/network/interfaces

**Comment by skamithi** [comment]
PR created. https://github.com/CumulusNetworks/cumulus-linux-ansible-modules/pull/24
