### ISSUE TITLE
Feature Request: cl_license should provide error if license requires EULA

### ISSUE THREAD

**Issue by trapier** [CumulusNetworks/cumulus-linux-ansible-modules#29]
cl_license currently hangs if the license requires agreement to the EULA.  

It would be better if it errored out and provided an error message to open a support case or contact licensing@cumulusnetworks.com.

**Comment by trapier** [comment]
More info here https://support.cumulusnetworks.com/hc/en-us/articles/202934753-EULA-Prompts-Interfere-with-Zero-Touch-Provisioning

**Comment by skamithi** [comment]
closing this ticket. addressing the problem from the cl_license tool perspective. change on automation tool may just be an option on cl_license that will  error out if EULA prompt is required.
