### ISSUE TITLE
Getting a with_dict error when reading through dict:

### ISSUE THREAD

**Issue by mirzawaqasahmed** [CumulusNetworks/cumulus-linux-ansible-modules#50]
Hi everyone,
This may not be an issue on the module but certainly for me and I hope I can get an answer from here.
I am trying to run a play book with variables defined in group_vars folder. however when I run the playbook Ansible throws an error saying "fatal: [spine111] => with_dict expects a dict".
What am I doing wrong?
My /roles/tasks/main.yml is:
- name: peerlink.4094 configuration for peer1 only
  cl_interface:
    name: "{{ item.key }}"
    ipv4: "{{ item.value.ipv4 }}"
    alias_name: "{{ item.value.alias_name }}"
    clagd_enable: "{{ item.value.clagd_enable }}"
    clagd_peer_ip: "{{ item.value.clagd_peer_ip }}"
    clagd_priority: "{{ item.value.clagd_priority }}"
    clagd_sys_mac: "{{ item.value.clagd_sys_mac }}"
    clagd_args: "{{ item.value.clagd_args }}"
    applyconfig: 'yes'
  with_dict: cl_interfaces[inventory_hostname]
  notify: reload networking
  tags: clagd

And my group_vars/peer output is:
cl_interface:
  spine111:
    peerlink.4094:
      alias_name: "Clag_PeerLink"
      ipv4: "169.254.1.1/30"
      clagd_enable: "yes"
      clagd_peer_ip: "169.254.1.2"
      clagd_priority: "4096"
      clagd_args: "-vm"
      clagd_sys_mac: "00:00:00:00:00:01"

What am I doing wrong here?

Thanks in advance...

**Comment by 8bitdad** [comment]
Mirza,

The process is having a hard time processing the [ ] in the string. It is expecting a dictionary return. What are you trying to reference in that statement? Can you restate that string?

**Comment by mirzawaqasahmed** [comment]
I am assuming that with_dict: cl_interfaces[inventory_hostname] will look a variable file in group_vars

hence in group_vars I have created a file named peer1 which represents the dict I pasted above.

so if my understanding serves me correctly when the play is run it will go to item which is now cl_interface and corresponding host which is spine111 and populate the values.

am i making sense?

**Comment by mirzawaqasahmed** [comment]
I am pasting the text again, as I messed up the format before.... Sorry for that.
This is the play book:

    ---
    # This file will take care of building peerlink.4094 on peer1 hosts only
    - hosts: peer1
      gather_facts: no
      roles:
        - clag-peer1

This is tasks file in the roles/peer1

---
        # tasks file for clag-peer1
        - name: peerlink.4094 configuration for peer1 only
          cl_interface:
            name: "{{ item.key }}"
            ipv4: "{{ item.value.ipv4 }}"
            alias_name: "{{ item.value.alias_name }}"
            clagd_enable: "{{ item.value.clagd_enable }}"
            clagd_peer_ip: "{{ item.value.clagd_peer_ip }}"
            clagd_priority: "{{ item.value.clagd_priority }}"
            clagd_sys_mac: "{{ item.value.clagd_sys_mac }}"
            clagd_args: "{{ item.value.clagd_args }}"
            applyconfig: 'yes'
          with_dict: cl_interfaces[inventory_hostname]
          notify: reload networking
          tags: clagd

Variable file named peer1 in group_vars has the following contents:

    cl_interface:
      - spine111:
            peerlink.4094:
                alias_name: "Clag_PeerLink"
                ipv4: "169.254.1.1/30"
                clagd_enable: "yes"
                clagd_peer_ip: "169.254.1.2"
                clagd_priority: "4096"
                clagd_args: "-vm"
                clagd_sys_mac: "00:00:00:00:00:01"

**Comment by mirzawaqasahmed** [comment]
I found the answer with the help of Jason https://community.cumulusnetworks.com/cumulus/topics/getting-a-with-dict-error-when-reading-through-dict

There was an additional "s" when the discretionary was being called. :(

And by the way there was one more error in my variable file that was related to indenting... I had 2 spaces instead of 4 :(

Thanks Scott for the help...
