### ISSUE TITLE
Push version 2.2.2 to Ansible Galaxy

### ISSUE THREAD

**Issue by davidmnoriega** [CumulusNetworks/cumulus-linux-ansible-modules#57]
Ansible Galaxy only has up to version 2.2.1 available, it could be the link between Ansible Galaxy and the repo has broken down. Can someone push 2.2.2?

**Comment by davidmnoriega** [comment]
Actually, I'm parsing through how https://github.com/CumulusNetworks/cldemo-automation-ansible works without using the ansible modules, making this less important

**Comment by isharacomix** [comment]
Good to hear! Either way, the cumulus modules are in core ansible now, so we are no longer pushing them to Galaxy. If you get the newest version of Ansible, you'll get the newest version of the modules as well.
