### ISSUE TITLE
any plans to add VRF membership for cl_bond and cl_interface?

### ISSUE THREAD

**Issue by wmclendon** [CumulusNetworks/cumulus-linux-ansible-modules#66]
hello,

now that cumulus linux supports VRFs, are there any plans to add specifying VRF membership as a value for cl_bond and cl_interface?

Thanks.

**Comment by ericpulvino** [comment]
Not at this time. These modules were/are supported through 2.5.x, there are no plans at this time to enhance these modules further to support newer 3.x functionality. I recommend using the template module when working with 3.x+. It's not that we don't want to, we just have to prioritize the work on these modules versus product features.
